theme: jekyll-theme-slate
title: Cloud Craftsmanship Manifesto
description: While the term craftsmanship and crafts is sometimes associated with with quint and outdates activities such as cheese making or basket knitting, we feel that the paradigm of applying obtained skills, knowledge and aptitude as well as a little tradition, perfectly applies to delivering high quality IT service with cloud technologies.
show_downloads: false
google_analytics: UA-9241787-2
